src_path: PATH_TO_PROJECT
app_rel_path: build
server_app: server
client_app: client

# for SSH remote
username: xxx
password: xxx

servers:
  - ip: 10.0.2.135
    numa_id: 0
  - ip: 10.0.2.130
    numa_id: 0
  - ip: 10.0.2.137
    numa_id: 0

clients:
  - ip: 10.0.2.130
    numa_id: 0
  - ip: 10.0.2.137
    numa_id: 0
  - ip: 10.0.2.135
    numa_id: 0
  - ip: 10.0.2.136
    numa_id: 0
  - ip: 10.0.2.130
    numa_id: 1
  - ip: 10.0.2.137
    numa_id: 1
  - ip: 10.0.2.135
    numa_id: 1
  - ip: 10.0.2.136
    numa_id: 1
